### ISSUE TITLE
Question about parallel job

### ISSUE THREAD

**Issue by dsiperek-vendavo** [KyMidd/AzureDevOps_Terraform_ResourceType_AutoApprovals#1]
First off great examples!!!!  I do have a question and wondering how you would handle it and not sure where to ask this question.  Lot of terraform setups split out resources / instances into subfolders. 
Say a terraform layout looks something like this:
backend\region\main.tf (backend servers in that region constructed from modules)
clients\region\clientname\main.tf (100 plus different clientname directories)
modules\modulefiles.tf (nsg,instance module, etc)
For the pipeline if a change is made to modules nsg for example it would need to be run on each client.  How would you handle this? I was thinking some how make parallel? This way multiple jobs can be run at once for different clients? 
On bash its easy to go through all them all but doing one at a time can take an hour or more depending on the number of clients in a given region. Below is an example how one could loop through the clients one at a time by running something like this in the region directory.
for d in ./*/; do (cd "$d" && echo "$d" && terraform plan); done
This again takes a long time.  In a pipeline how would you handle something like this?

**Comment by KyMidd** [comment]
Parallelization is a neat topic. The easiest solve is to have many pipelines. You could alternatively use a tool that can run lots of pipelines in parallel natively, like TerraGrunt (https://terragrunt.gruntwork.io/). 

Yeah, bash loops aren't inherently parallel friendly. I recommend the options above. 

As a far-left-field alternative. If you want to test a specific module, you could write testing around that particular module in isolation, alla "unit testing", with TerraTest or a module-specific testing pipeline. That way you can make sure code is valid and correct as a single, divorced unit, then deploy it once ready to all your pipelines (even if they take an hour to run to apply). 

Let me know if I can help more!
